pipeline {
    environment { 
      registry = "adiyv/primecheckjava2"
         registryCrendential = 'dockerhub'
    }
    agent any
    stages {
        stage('Building an image') {
            steps {
                script{
                  docker.build registry + "$BUILD_NUMBER"
            }
         }
        }
    }
}

